"""
File: printdata.py
Create Date: 2024-10-23
Description:
    - This script loads and prints all arrays generated by data_generation.py.
    - It traverses through all groups G0 to G9 and arrays A0 to A7 within each group.
"""

import numpy as np
import os

# Number of groups Gj to process
num_groups = 1

# Number of arrays Ai in each group
num_arrays = 8

# Loop over each group Gj
for group_index in range(num_groups):
    current_dir = os.path.dirname(__file__)
    group_dir = os.path.join(current_dir, '..', 'data', f'G{group_index}')
    print(f'----- Group G{group_index} -----')
    
    # Loop over each array Ai in the group
    for array_index in range(num_arrays):
        array_filename = os.path.join(group_dir, f'A{array_index}.npy')
        
        # Check if the file exists
        if os.path.exists(array_filename):
            # Load the array from the .npy file
            Ai = np.load(array_filename)
            
            # Print array information
            print(f'Array A{array_index} in Group G{group_index}:')
            print(f'Shape: {Ai.shape}, Data Type: {Ai.dtype}')
            print('Values:')
            print(Ai)
            print('')  # Add an empty line for readability
        else:
            print(f'Array A{array_index} in Group G{group_index} does not exist.')
